- include/boost/parameter/aux_/arg_list.hpp
Add the assert to avoid ugly message when invoked `arg_list<>::operator[](lazy_default<>)` with `maybe<>`
> improve aux::arg_list<>::operator[]()

- include/boost/parameter/aux_/unwrap_cv_reference.hpp
- test/unwrap_cv_reference.cpp
Add support for std::reference_wrapper<> and std::ref().
>  Upgrade boost::parameter::aux::unwrap_cv_reference

- .travis.yml
- appveyor.yml
- include/boost/parameter/aux_/tagged_argument.hpp
- test/Jamfile.v2
- test/compose.cpp
Add support for passing functions as arguments to Boost.Parameter-enabled functions.
>  Upgrade boost::parameter::aux::tagged_argument

- doc/html/index.html
- doc/html/reference.html
- doc/index.rst
- doc/reference.rst
- include/boost/parameter/aux_/preprocessor/impl/forwarding_overloads.hpp
- include/boost/parameter/aux_/preprocessor/qualifier.hpp
- include/boost/parameter/keyword.hpp
- include/boost/parameter/keyword_fwd.hpp
- include/boost/parameter/name.hpp
- test/Jamfile.v2
- test/compose.cpp
- test/literate/handling-out-parameters0.cpp
- test/literate/optional-parameters0.cpp
- test/literate/predicate-requirements0.cpp
- test/literate/writing-the-function0.cpp
Add parameter category qualifier "forward" (current qualifiers are "in", "out", and "in_out") based on http://www.modernescpp.com/index.php/c-core-guidelines-how-to-pass-function-parameters.  Add new usage syntax BOOST_PARAMETER_NAME((object-name), namespace-name) qualifier(tag-name)) and BOOST_PARAMETER_NAME(qualifier(name)).  (Existing code that uses qualifiers directly and correctly with BOOST_PARAMETER_FUNCTION and other code generation macros should remain unaffected for now, so no breaking changes.)  The reason for the change in usage is to enable applying of parameter category constraints to Boost.Parameter-enabled functions and constructors invoked through argument composition.  (Otherwise, it is currently possible to use argument composition to bypass parameter category …
>  Support additional parameter categories

- doc/html/reference.html
- doc/reference.rst
- include/boost/parameter.hpp
- include/boost/parameter/aux_/tagged_argument.hpp
- include/boost/parameter/nested_keyword.hpp
- test/compose.cpp
Upon approval and merging of this PR, replace the definition of BOOST_PARAMETER_NESTED_KEYWORD in <boost/accumulators/accumulators_fwd.hpp> with #include <boost/parameter/nested_keyword.hpp>.
>  Add keyword generation macro BOOST_PARAMETER_NESTED_KEYWORD

- include/boost/parameter/aux_/tagged_argument.hpp
- test/compose.cpp
I'm still in the process of fixing compiler errors that are showing up in the BGL test suite.  I've tracked a couple of them down to "libs/graph/test/isomorphism.hpp", line 532, which reads, in part:
arg_pack[_vertex_max_invariant | (invariant2.max)()]
For compilers that support perfect forwarding, arg_pack is an object of type boost::parameter::aux::tagged_argument_rref<...>, but the [] operand evaluates to an object of type boost::parameter::aux::default_<...>, not boost::parameter::aux::default_r_<...>.  This PR aims to correct the deficiency by adding the missing overloads.
>  Add missing boost::parameter::aux::tagged_argument_rref::operator[] overloads

- doc/html/index.html
- doc/index.rst
- test/literate/deduced-parameters0.cpp
- test/literate/default-expression-evaluation0.cpp
- test/literate/parameter-enabled-member-functions0.cpp
- test/literate/static-member-functions0.cpp
- test/literate/top-level0.cpp
* Fix compiler failures showing up on regression test matrix due to void return type.
* Fix gcc-3.4 failures showing up regression test matrix due to binding string literals to non-const references to char const*.
* Update tutorial documentation to match literate tests.
> Update literate tests and tutorial documentation

- include/boost/parameter/aux_/arg_list.hpp
- include/boost/parameter/aux_/pack/deduce_tag.hpp
- include/boost/parameter/aux_/pack/make_arg_list.hpp
- include/boost/parameter/aux_/pack/satisfies.hpp
- test/preprocessor_deduced.cpp
Enable preprocessor-generated function call operator overloads & overloads of the same name to coexist even with deduced arguments.  SFINAE required.
>  Upgrade code generation macros

- include/boost/parameter/config.hpp
- include/boost/parameter/parameters.hpp
<boost/parameter/config.hpp>
* Introduce configuration macros BOOST_PARAMETER_CAN_USE_MP11 and BOOST_PARAMETER_DISABLE_MP11_USAGE.
* Update perfect forwarding support requirements to fix regressions on test matrix.
<boost/parameter/parameters.hpp>
* Allow mp11::mp_list to be default parameter_spec type if available.
>  Introduce support for Boost.MP11

- include/boost/parameter/aux_/unwrap_cv_reference.hpp
- test/normalized_argument_types.cpp
* Fix compiler error: base `boost::reference_wrapper<int>' with only non-default constructor in class without a constructor.
* Ignore normalized_argument_types test failures.
>  Add workarounds for GCC 3.x or earlier

- include/boost/parameter.hpp
- include/boost/parameter/are_tagged_arguments.hpp
- include/boost/parameter/aux_/preprocessor/impl/forwarding_overloads.hpp
- include/boost/parameter/aux_/preprocessor/impl/function_dispatch_layer.hpp
- include/boost/parameter/aux_/preprocessor/impl/function_dispatch_tuple.hpp
- include/boost/parameter/aux_/preprocessor/impl/function_name.hpp
- include/boost/parameter/aux_/preprocessor/impl/no_spec_overloads.hpp
- include/boost/parameter/aux_/preprocessor/impl/specification.hpp
- include/boost/parameter/compose.hpp
- include/boost/parameter/preprocessor.hpp
- include/boost/parameter/preprocessor_no_spec.hpp
- test/Jamfile.v2
- test/evaluate_category_10.cpp
- test/parameterized_inheritance.cpp
- test/preprocessor.cpp
- test/preprocessor_eval_cat_8.cpp
- test/preprocessor_eval_cat_no_spec.cpp
* Add variadic metafunction boost::parameter::are_tagged_arguments to help improve overload resolution capabilities.  Used by compose() and the new BOOST_PARAMETER_NO_SPEC_* code generation macros.
* Add variadic function template compose() which takes in named arguments and returns them in an argument pack.
* Add code generation macros BOOST_PARAMETER_BASIC_FUNCTION_CALL_OPERATOR, BOOST_PARAMETER_BASIC_CONST_FUNCTION_CALL_OPERATOR, BOOST_PARAMETER_NO_SPEC_FUNCTION, BOOST_PARAMETER_NO_SPEC_MEMBER_FUNCTION, BOOST_PARAMETER_NO_SPEC_CONST_MEMBER_FUNCTION, BOOST_PARAMETER_NO_SPEC_FUNCTION_CALL_OPERATOR, BOOST_PARAMETER_NO_SPEC_CONST_FUNCTION_CALL_OPERATOR, BOOST_PARAMETER_NO_SPEC_CONSTRUCTOR, and BOOST_PARAMETER_NO_SPEC_NO_BASE_CONSTRUCTOR.
> Add are_tagged_arguments<>, compose(), and code generation macros

- test/Jamfile.v2
- test/compose.cpp
- test/evaluate_category.cpp
- test/literate/parameter-enabled-function-call-operators0.cpp
- test/preprocessor_deduced.cpp
- test/preprocessor_eval_cat_no_spec.cpp
- test/preprocessor_eval_category.cpp
* Add "test/literate/parameter-enabled-function-call-operators0.cpp" to test suite under alias 'parameter_literate_tests'.
* Add compose() test routine to "test/compose.cpp"
* Replace LIBS_PARAMETER_TEST_COMPILE_FAILURE_MSVC with LIBS_PARAMETER_TEST_COMPILE_FAILURE_VENDOR_SPECIFIC in case compilers other than MSVC start exhibiting errant behavior.
* Adjust for the fact that BOOST_PARAMETER_MAX_ARITY is defined regardless of whether or not BOOST_PARAMETER_HAS_PERFECT_FORWARDING is defined.
* Use minimal file headers to #include vice <boost/parameter.hpp>.
> Update test suite

- include/boost/parameter/aux_/arg_list.hpp
- include/boost/parameter/aux_/default.hpp
- include/boost/parameter/aux_/tagged_argument.hpp
- include/boost/parameter/aux_/use_default_tag.hpp
- include/boost/parameter/compose.hpp
- include/boost/parameter/keyword.hpp
- include/boost/parameter/name.hpp
- include/boost/parameter/nested_keyword.hpp
- include/boost/parameter/parameters.hpp
The reference documentation specifies this for some of the constructors and functions.
>  Qualify applicable constructors & functions with BOOST_CONSTEXPR

- doc/html/index.html
- doc/html/reference.html
- doc/index.rst
- doc/reference.rst
- include/boost/parameter/aux_/preprocessor/impl/no_spec_overloads.hpp
- include/boost/parameter/aux_/preprocessor/impl/parenthesized_return_type.hpp
- include/boost/parameter/aux_/preprocessor/impl/parenthesized_type.hpp
- include/boost/parameter/preprocessor.hpp
- test/Jamfile.v2
- test/preprocessor_deduced.cpp
The code generation macros are supposed to support parameter-dependent return types, but it turns out that they currently don't really do that.  This commit fixes the issue.
> Improve support for parameter-dependent return types of functions generated by preprocessor macros

- include/boost/parameter/config.hpp
In my GitHub fork of Boost.Graph, I've been upgrading some algorithms to use BOOST_PARAMETER_FUNCTION, but MinGW with GCC 5.3.0 has been running out of heap space on some of the affected tests.  The goal of this commit is to eliminate these occurrences.
> Set BOOST_PARAMETER_COMPOSE_MAX_ARITY to 20 for MinGW

- doc/html/reference.html
- doc/reference.rst
- include/boost/parameter/compose.hpp
Some Boost.Graph algorithms return one of their optional named function parameters.  If the user doesn't specify the parameter, then the default return type must necessarily be different.  This metafunction is needed to help facilitate computation of such a return type without resorting to decltype(), which not all compilers support.
> Add metafunction result_of::compose

- CMakeLists.txt
- test/CMakeLists.txt
Functionality:
- CMake file only supports add_subdirectory workflow.
- Provides target `Boost::parameter` to "link" against (effectively providing the include directory of parameter and information about its dependencies).
- Allows compilation and running of most of the unit tests. 
- Doesn't support installation (That is taken care of via b2).
For basic testing:
1) Make sure you have checked out the latest (develop) version of all other boost libraries you are depending on (directly or indirectly) into sibling folders of this library (e.g. recursively check out branch develop of boostorg/boost).
2) Copy a file like the one in: https://github.com/boostorg/boost/pull/193/files into the boost root directory. Essentially, that file will simply call `add_subdirectory( )` on all boost …
> Add minimal cmake support

- .travis.yml
* Add clang++-6.0 with cxxstd=2a for linux, clang++-7 for linux, and clang++-8 for linux to test matrix.
* Change sources to adapt to change in Travis Cl test environment from "trusty" to "xenial".
> Upgrade .travis.yml

- include/boost/parameter/aux_/tagged_argument.hpp
In C++11 mode, when named parameter pack was a single tagged argument, parameter value was not extracted when an rvalue default value was provided by the user (instead, the default value was returned). This commit adds a missing overload for `default_r_`, which returns the parameter
value.
Fixes https://github.com/boostorg/parameter/issues/97.
> Fix argument value selection with an rvalue default

- include/boost/parameter/aux_/default.hpp
The default compiler-generated move constructor on MSVC 2015
does not move the Rvalue references correctly.
Fixes boostorg/log#132
> Fix default_r_ move constructor on MSVC 2015

- test/Jamfile.v2
This removes the superfluous test project ID that will conflict with the modular project IDs for all libraries. When libraries are modular they will have the standard global ID of /boost/*lib-name*. Having colliding IDs will cause build errors.
#modular-boost https://github.com/users/grafikrobot/projects/1
> This removes test project ID that will conflict with modular ID.
